version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building image
          command: docker build -t wood1y/syno-audio:prod .
