version: 2
jobs:
  # build:
    # docker:
    #   - image: circleci/node
    # steps:
    #   - checkout
    #   - setup_remote_docker
    #   - run:
    #       name: Building image
    #       command: docker build -t wood1y/syno-audio:prod .
  build:
    docker:
      - image: circleci/node
    steps: 
      - checkout
      - run:
          name: Installing Heroku cli
          command: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Heroku login
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Pushing image to Heroku registry
          command: heroku container:push web -a syno-audio
      - run:
          name: Deploying
          command: heroku container:release web -a syno-audio

