version: 2
jobs:
  # build:
    # docker:
    #   - image: circleci/node
    # steps:
    #   - checkout
  build:
    docker:
      - image: circleci/node
    steps: 
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Installing Heroku cli
          command: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Heroku login
          command: bash .circleci/setup-heroku.sh
          command: heroku container:login
      - run:
          name: Pushing image to Heroku registry
          command: heroku container:push web -a syno-audio
      - run:
          name: Deploying
          command: heroku container:release web -a syno-audio


      # - run:
      #     name: Building image
      #     command: docker build -t wood1y/syno-audio:prod .
      # - run:
      #     name: Pushing image to Heroku registry
      #     command: docker tag wood1y/syno-audio:prod registry.heroku.com/syno-audio/web
      # - run:
      #     name: Deploying
      #     command: docker push registry.heroku.com/syno-audio/web


