version: 2
jobs:
  # build:
    # docker:
    #   - image: circleci/node
    # steps:
    #   - checkout
  build:
    docker:
      - image: circleci/node
    steps: 
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Installing Heroku cli
      #     command: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      # - run:
      #     name: Heroku login
      #     command: bash .circleci/setup-heroku.sh
      - run:
          name: Building image
          command: docker build -t wood1y/syno-audio:prod .
      - run:
          name: Pushing image to Heroku registry
          command: docker tag syno-audio registry.heroku.com/syno-audio/web
      - run:
          name: Deploying
          command: docker push registry.heroku.com/syno-audio/web


