version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps: 
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Installing Heroku cli
          command: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Setting up Heroku CLI credentials
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Heroku login
          command: heroku container:login
      - run:
          name: Pushing image to Heroku registry
          command: heroku container:push web -a syno-audio
  deploy:
    machine: true
    steps:
      - run:
          name: Deploying
          command: heroku container:release web -a syno-audio



